name             'sprout-wrap'
maintainer       'Kaleb Walton'
maintainer_email 'kalebwalton@gmail.com'
license          'MIT'
description      'Kalebs sprout wrap'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
supports         'mac_os_x'
depends          'osx'
depends          'sprout-base'
